/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.22
 * Generated at: 2026-06-16 07:16:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>实验六 JSP内置对象的应用</title>\n");
      out.write("    <style>\n");
      out.write("        body { font-family: Arial, sans-serif; margin: 20px auto; width: 700px; }\n");
      out.write("        h1 { text-align: center; color: #333; }\n");
      out.write("        .section { background: #f5f5f5; padding: 15px; margin: 10px 0; border-radius: 8px; border-left: 4px solid #009966; }\n");
      out.write("        .section h3 { color: #006633; margin-top: 0; }\n");
      out.write("        table { border-collapse: collapse; width: 100%; }\n");
      out.write("        table, th, td { border: 1px solid #ddd; }\n");
      out.write("        th, td { padding: 8px; text-align: left; }\n");
      out.write("        th { background-color: #009966; color: white; width: 30%; }\n");
      out.write("        pre { background: #e8e8e8; padding: 10px; border-radius: 4px; font-size: 12px; overflow-x: auto; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <h1>JSP内置对象的应用</h1>\n");
      out.write("\n");
      out.write("    <!-- 1. request 对象 -->\n");
      out.write("    <div class=\"section\">\n");
      out.write("        <h3>1. request 对象 (HttpServletRequest)</h3>\n");
      out.write("        <table>\n");
      out.write("            <tr><th>属性</th><th>值</th></tr>\n");
      out.write("            <tr><td>客户端IP地址</td><td>");
      out.print( request.getRemoteAddr() );
      out.write("</td></tr>\n");
      out.write("            <tr><td>客户端主机名</td><td>");
      out.print( request.getRemoteHost() );
      out.write("</td></tr>\n");
      out.write("            <tr><td>请求方法</td><td>");
      out.print( request.getMethod() );
      out.write("</td></tr>\n");
      out.write("            <tr><td>请求URL</td><td>");
      out.print( request.getRequestURL() );
      out.write("</td></tr>\n");
      out.write("            <tr><td>请求URI</td><td>");
      out.print( request.getRequestURI() );
      out.write("</td></tr>\n");
      out.write("            <tr><td>协议</td><td>");
      out.print( request.getProtocol() );
      out.write("</td></tr>\n");
      out.write("            <tr><td>服务器名</td><td>");
      out.print( request.getServerName() );
      out.write("</td></tr>\n");
      out.write("            <tr><td>服务器端口</td><td>");
      out.print( request.getServerPort() );
      out.write("</td></tr>\n");
      out.write("            <tr><td>字符编码</td><td>");
      out.print( request.getCharacterEncoding() );
      out.write("</td></tr>\n");
      out.write("        </table>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- 2. response 对象 -->\n");
      out.write("    <div class=\"section\">\n");
      out.write("        <h3>2. response 对象 (HttpServletResponse)</h3>\n");
      out.write("        <table>\n");
      out.write("            <tr><th>属性</th><th>值</th></tr>\n");
      out.write("            <tr><td>内容类型</td><td>");
      out.print( response.getContentType() );
      out.write("</td></tr>\n");
      out.write("            <tr><td>缓冲区大小</td><td>");
      out.print( response.getBufferSize() );
      out.write(" bytes</td></tr>\n");
      out.write("            <tr><td>字符编码</td><td>");
      out.print( response.getCharacterEncoding() );
      out.write("</td></tr>\n");
      out.write("        </table>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- 3. session 对象 -->\n");
      out.write("    <div class=\"section\">\n");
      out.write("        <h3>3. session 对象 (HttpSession)</h3>\n");
      out.write("        ");

            String visitTime = (String) session.getAttribute("firstVisit");
            if (visitTime == null) {
                visitTime = new java.util.Date().toString();
                session.setAttribute("firstVisit", visitTime);
            }
            Integer sessionCount = (Integer) session.getAttribute("count");
            if (sessionCount == null) {
                sessionCount = 1;
            } else {
                sessionCount++;
            }
            session.setAttribute("count", sessionCount);
        
      out.write("\n");
      out.write("        <table>\n");
      out.write("            <tr><th>属性</th><th>值</th></tr>\n");
      out.write("            <tr><td>Session ID</td><td>");
      out.print( session.getId() );
      out.write("</td></tr>\n");
      out.write("            <tr><td>创建时间</td><td>");
      out.print( new java.util.Date(session.getCreationTime()) );
      out.write("</td></tr>\n");
      out.write("            <tr><td>首次访问时间</td><td>");
      out.print( visitTime );
      out.write("</td></tr>\n");
      out.write("            <tr><td>本次会话访问次数</td><td>");
      out.print( sessionCount );
      out.write("</td></tr>\n");
      out.write("            <tr><td>最大不活动间隔</td><td>");
      out.print( session.getMaxInactiveInterval() );
      out.write(" 秒</td></tr>\n");
      out.write("        </table>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- 4. application 对象 -->\n");
      out.write("    <div class=\"section\">\n");
      out.write("        <h3>4. application 对象 (ServletContext)</h3>\n");
      out.write("        ");

            Integer appCount = (Integer) application.getAttribute("appCount");
            if (appCount == null) {
                appCount = 1;
            } else {
                appCount++;
            }
            application.setAttribute("appCount", appCount);
        
      out.write("\n");
      out.write("        <table>\n");
      out.write("            <tr><th>属性</th><th>值</th></tr>\n");
      out.write("            <tr><td>服务器信息</td><td>");
      out.print( application.getServerInfo() );
      out.write("</td></tr>\n");
      out.write("            <tr><td>Servlet API版本</td><td>");
      out.print( application.getMajorVersion() );
      out.write('.');
      out.print( application.getMinorVersion() );
      out.write("</td></tr>\n");
      out.write("            <tr><td>应用全局访问次数</td><td>");
      out.print( appCount );
      out.write("</td></tr>\n");
      out.write("            <tr><td>真实路径(/)</td><td>");
      out.print( application.getRealPath("/") );
      out.write("</td></tr>\n");
      out.write("        </table>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- 5. request、session、application 区别 -->\n");
      out.write("    <div class=\"section\">\n");
      out.write("        <h3>5. request vs session vs application 的区别</h3>\n");
      out.write("        <table>\n");
      out.write("            <tr><th>作用域</th><th>范围</th><th>生命周期</th></tr>\n");
      out.write("            <tr>\n");
      out.write("                <td>request</td>\n");
      out.write("                <td>单次请求</td>\n");
      out.write("                <td>请求处理完成后消失</td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td>session</td>\n");
      out.write("                <td>单次会话</td>\n");
      out.write("                <td>用户关闭浏览器或session超时时消失</td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td>application</td>\n");
      out.write("                <td>整个Web应用</td>\n");
      out.write("                <td>服务器重启或应用重新加载时消失</td>\n");
      out.write("            </tr>\n");
      out.write("        </table>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <p style=\"text-align:center; color:#888; font-size:12px; margin-top:20px;\">\n");
      out.write("        实验六：JSP内置对象 (request, response, session, application) 的应用\n");
      out.write("    </p>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
