/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.22
 * Generated at: 2026-06-16 07:26:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class shop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>简单购物车 - Session应用</title>\n");
      out.write("    <style>\n");
      out.write("        body { font-family: Arial, sans-serif; margin: 20px auto; width: 600px; }\n");
      out.write("        h2 { text-align: center; }\n");
      out.write("        .product { background: #f5f5f5; padding: 10px; margin: 10px 0; border-radius: 8px; display: flex; justify-content: space-between; align-items: center; }\n");
      out.write("        .product span { font-size: 16px; }\n");
      out.write("        .cart { background: #e8f5e9; padding: 15px; border-radius: 8px; margin-top: 20px; }\n");
      out.write("        .cart h3 { margin-top: 0; color: #006633; }\n");
      out.write("        .btn {\n");
      out.write("            padding: 6px 15px; background: #009966; color: white; border: none;\n");
      out.write("            border-radius: 4px; cursor: pointer; text-decoration: none; font-size: 13px;\n");
      out.write("        }\n");
      out.write("        .btn:hover { background: #007a4d; }\n");
      out.write("        .clear-btn { background: #f44336; }\n");
      out.write("        .clear-btn:hover { background: #da190b; }\n");
      out.write("        table { width: 100%; border-collapse: collapse; margin-top: 10px; }\n");
      out.write("        th, td { border: 1px solid #ddd; padding: 6px; text-align: center; }\n");
      out.write("        th { background: #009966; color: white; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <h2>简单购物车 (Session对象应用)</h2>\n");
      out.write("\n");
      out.write("    ");

        // 使用session保存购物车
        java.util.Map<String, Integer> cart = (java.util.Map<String, Integer>) session.getAttribute("cart");
        if (cart == null) {
            cart = new java.util.HashMap<String, Integer>();
            session.setAttribute("cart", cart);
        }

        // 处理添加商品
        String addItem = request.getParameter("add");
        if (addItem != null && !addItem.isEmpty()) {
            cart.put(addItem, cart.getOrDefault(addItem, 0) + 1);
        }
        // 处理清空购物车
        String clear = request.getParameter("clear");
        if (clear != null) {
            cart.clear();
        }
    
      out.write("\n");
      out.write("\n");
      out.write("    <h3>商品列表：</h3>\n");
      out.write("    <div class=\"product\">\n");
      out.write("        <span>📕 Java编程思想</span>\n");
      out.write("        <a href=\"?add=Java编程思想\" class=\"btn\">加入购物车</a>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"product\">\n");
      out.write("        <span>📗 JSP实战指南</span>\n");
      out.write("        <a href=\"?add=JSP实战指南\" class=\"btn\">加入购物车</a>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"product\">\n");
      out.write("        <span>📘 Servlet核心技术</span>\n");
      out.write("        <a href=\"?add=Servlet核心技术\" class=\"btn\">加入购物车</a>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"product\">\n");
      out.write("        <span>📙 Web开发大全</span>\n");
      out.write("        <a href=\"?add=Web开发大全\" class=\"btn\">加入购物车</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"cart\">\n");
      out.write("        <h3>购物车内容：</h3>\n");
      out.write("        ");
 if (cart.isEmpty()) { 
      out.write("\n");
      out.write("            <p>购物车为空</p>\n");
      out.write("        ");
 } else { 
      out.write("\n");
      out.write("            <table>\n");
      out.write("                <tr><th>商品名称</th><th>数量</th></tr>\n");
      out.write("                ");

                    for (java.util.Map.Entry<String, Integer> entry : cart.entrySet()) {
                        out.println("<tr><td>" + entry.getKey() + "</td><td>" + entry.getValue() + "</td></tr>");
                    }
                
      out.write("\n");
      out.write("            </table>\n");
      out.write("            <p>总计：<strong>");
      out.print( cart.size() );
      out.write("</strong> 种商品</p>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        <a href=\"?clear=true\" class=\"btn clear-btn\">清空购物车</a>\n");
      out.write("        <a href=\"index.jsp\" class=\"btn\">返回首页</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <p style=\"margin-top:15px; font-size:12px; color:#888;\">\n");
      out.write("        Session ID: ");
      out.print( session.getId() );
      out.write("<br>\n");
      out.write("        购物车数据存储在HttpSession对象中\n");
      out.write("    </p>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
