/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.22
 * Generated at: 2026-06-16 07:32:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

    String username = (String) session.getAttribute("username");
    if (username == null) {
        response.sendRedirect(response.encodeRedirectURL("login.jsp?error=请先登录！"));
        return;
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>个人信息 - 会话跟踪系统</title>\n");
      out.write("    <style>\n");
      out.write("        body { font-family: Arial, sans-serif; margin: 30px auto; width: 550px; }\n");
      out.write("        h1 { text-align: center; color: #2196F3; }\n");
      out.write("        .profile-box { background: #e3f2fd; padding: 25px; border-radius: 8px; border: 2px solid #2196F3; }\n");
      out.write("        .info-table { width: 100%; border-collapse: collapse; margin: 15px 0; }\n");
      out.write("        .info-table th, .info-table td { padding: 8px; border: 1px solid #ddd; text-align: left; }\n");
      out.write("        .info-table th { background: #2196F3; color: white; width: 35%; }\n");
      out.write("        .nav-links { display: flex; justify-content: center; gap: 15px; margin-top: 20px; }\n");
      out.write("        .nav-links a { padding: 10px 20px; text-decoration: none; border-radius: 4px; font-size: 14px; }\n");
      out.write("        .home-btn { background: #009966; color: white; }\n");
      out.write("        .logout-btn { background: #f44336; color: white; }\n");
      out.write("        .nav-links a:hover { opacity: 0.8; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <h1>个人信息中心</h1>\n");
      out.write("\n");
      out.write("    <div class=\"profile-box\">\n");
      out.write("        <h3 style=\"text-align:center;\">用户资料</h3>\n");
      out.write("        <table class=\"info-table\">\n");
      out.write("            <tr><th>属性</th><th>值</th></tr>\n");
      out.write("            <tr><td>用户名</td><td><strong>");
      out.print( username );
      out.write("</strong></td></tr>\n");
      out.write("            <tr><td>登录时间</td><td>");
      out.print( session.getAttribute("loginTime") );
      out.write("</td></tr>\n");
      out.write("            <tr><td>当前Session ID</td><td style=\"font-size:10px; word-break:break-all;\">");
      out.print( session.getId() );
      out.write("</td></tr>\n");
      out.write("            <tr><td>会话是否新建</td><td>");
      out.print( session.isNew() ? "是" : "否" );
      out.write("</td></tr>\n");
      out.write("            <tr><td>请求编码URL</td><td style=\"font-size:10px; word-break:break-all;\">");
      out.print( response.encodeURL("profile.jsp") );
      out.write("</td></tr>\n");
      out.write("        </table>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"nav-links\">\n");
      out.write("        <a href=\"");
      out.print( response.encodeURL("welcome.jsp") );
      out.write("\" class=\"home-btn\">返回首页</a>\n");
      out.write("        <a href=\"");
      out.print( response.encodeURL("logout") );
      out.write("\" class=\"logout-btn\">注销登录</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div style=\"margin-top:20px; font-size:12px; color:#888; padding:10px; background:#f9f9f9; border-radius:8px;\">\n");
      out.write("        <strong>会话跟踪技术说明：</strong><br>\n");
      out.write("        1. 本系统使用HttpSession进行会话跟踪<br>\n");
      out.write("        2. 用户信息保存在session对象中<br>\n");
      out.write("        3. 使用 response.encodeURL() 实现URL重写<br>\n");
      out.write("        4. 注销时调用 session.invalidate() 清除所有会话数据<br>\n");
      out.write("        5. 支持浏览器禁用Cookie的场景\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
