/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.22
 * Generated at: 2026-06-16 07:32:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

    // 检查是否已登录
    String username = (String) session.getAttribute("username");
    if (username == null) {
        // 未登录，使用URL重写进行重定向
        response.sendRedirect(response.encodeRedirectURL("login.jsp?error=请先登录！"));
        return;
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>欢迎 - 会话跟踪系统</title>\n");
      out.write("    <style>\n");
      out.write("        body { font-family: Arial, sans-serif; margin: 30px auto; width: 600px; }\n");
      out.write("        h1 { text-align: center; color: #006633; }\n");
      out.write("        .welcome-box { background: #e8f5e9; padding: 25px; border-radius: 8px; border: 2px solid #4CAF50; margin: 15px 0; }\n");
      out.write("        .info-table { width: 100%; border-collapse: collapse; margin: 15px 0; }\n");
      out.write("        .info-table th, .info-table td { padding: 8px; border: 1px solid #ddd; text-align: left; }\n");
      out.write("        .info-table th { background: #009966; color: white; width: 35%; }\n");
      out.write("        .nav-links { display: flex; justify-content: center; gap: 15px; margin-top: 20px; }\n");
      out.write("        .nav-links a { padding: 10px 20px; text-decoration: none; border-radius: 4px; font-size: 14px; }\n");
      out.write("        .profile-btn { background: #2196F3; color: white; }\n");
      out.write("        .logout-btn { background: #f44336; color: white; }\n");
      out.write("        .nav-links a:hover { opacity: 0.8; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <h1>欢迎使用会话跟踪系统</h1>\n");
      out.write("\n");
      out.write("    <div class=\"welcome-box\">\n");
      out.write("        <p style=\"font-size:18px; text-align:center;\">\n");
      out.write("            您好，<strong>");
      out.print( username );
      out.write("</strong>！欢迎回来！\n");
      out.write("        </p>\n");
      out.write("        <table class=\"info-table\">\n");
      out.write("            <tr><th>会话信息</th><th>值</th></tr>\n");
      out.write("            <tr><td>用户名</td><td><strong>");
      out.print( username );
      out.write("</strong></td></tr>\n");
      out.write("            <tr><td>Session ID</td><td style=\"font-size:11px; word-break:break-all;\">");
      out.print( session.getAttribute("sessionId") );
      out.write("</td></tr>\n");
      out.write("            <tr><td>登录时间</td><td>");
      out.print( session.getAttribute("loginTime") );
      out.write("</td></tr>\n");
      out.write("            <tr><td>Session创建时间</td><td>");
      out.print( new java.util.Date(session.getCreationTime()) );
      out.write("</td></tr>\n");
      out.write("            <tr><td>最后访问时间</td><td>");
      out.print( new java.util.Date(session.getLastAccessedTime()) );
      out.write("</td></tr>\n");
      out.write("            <tr><td>最大不活动间隔</td><td>");
      out.print( session.getMaxInactiveInterval() );
      out.write(" 秒</td></tr>\n");
      out.write("            <tr><td>当前时间</td><td>");
      out.print( new java.util.Date() );
      out.write("</td></tr>\n");
      out.write("        </table>\n");
      out.write("\n");
      out.write("        <p style=\"font-size:12px; color:#666; text-align:center;\">\n");
      out.write("            您的登录状态保存在HttpSession中<br>\n");
      out.write("            关闭浏览器或注销后，Session将失效\n");
      out.write("        </p>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"nav-links\">\n");
      out.write("        <a href=\"");
      out.print( response.encodeURL("profile.jsp") );
      out.write("\" class=\"profile-btn\">查看个人信息</a>\n");
      out.write("        <a href=\"");
      out.print( response.encodeURL("logout") );
      out.write("\" class=\"logout-btn\">注销登录</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <p style=\"text-align:center; color:#888; font-size:12px; margin-top:20px;\">\n");
      out.write("        所有链接使用 response.encodeURL() 进行URL重写<br>\n");
      out.write("        确保在浏览器禁用Cookie时仍能正常使用Session\n");
      out.write("    </p>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
