/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.22
 * Generated at: 2026-06-16 07:16:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class inputNumber_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>MVC模式 - 四则运算</title>\n");
      out.write("    <style>\n");
      out.write("        body { font-family: Arial, sans-serif; margin: 50px auto; width: 450px; }\n");
      out.write("        h2 { text-align: center; color: #333; }\n");
      out.write("        .calc-box { background: #f5f5f5; padding: 25px; border-radius: 8px; border: 1px solid #ddd; }\n");
      out.write("        .form-group { margin-bottom: 15px; }\n");
      out.write("        label { display: block; margin-bottom: 5px; font-weight: bold; }\n");
      out.write("        input[type=\"text\"], select {\n");
      out.write("            width: 95%; padding: 8px; border: 1px solid #ccc; border-radius: 4px;\n");
      out.write("        }\n");
      out.write("        select { width: 100%; }\n");
      out.write("        input[type=\"submit\"] {\n");
      out.write("            width: 100%; padding: 10px; background: #009966; color: white;\n");
      out.write("            border: none; border-radius: 4px; font-size: 16px; cursor: pointer; margin-top: 10px;\n");
      out.write("        }\n");
      out.write("        input[type=\"submit\"]:hover { background: #007a4d; }\n");
      out.write("        .model-info { font-size: 12px; color: #888; margin-top: 20px; text-align: center; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <h2>MVC模式 - 四则运算计算器</h2>\n");
      out.write("    <div class=\"calc-box\">\n");
      out.write("        <form action=\"handleComputer\" method=\"post\">\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label>第一个操作数：</label>\n");
      out.write("                <input type=\"text\" name=\"operand1\" placeholder=\"请输入第一个数字\" required>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label>运算符：</label>\n");
      out.write("                <select name=\"operator\">\n");
      out.write("                    <option value=\"+\">加法 (+)</option>\n");
      out.write("                    <option value=\"-\">减法 (-)</option>\n");
      out.write("                    <option value=\"*\">乘法 (×)</option>\n");
      out.write("                    <option value=\"/\">除法 (÷)</option>\n");
      out.write("                </select>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label>第二个操作数：</label>\n");
      out.write("                <input type=\"text\" name=\"operand2\" placeholder=\"请输入第二个数字\" required>\n");
      out.write("            </div>\n");
      out.write("            <input type=\"submit\" value=\"计算\">\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"model-info\">\n");
      out.write("        <p><strong>MVC模式说明：</strong></p>\n");
      out.write("        <p>M(Model): Computer.java (实体模型) + CalculateBean.java (业务模型)</p>\n");
      out.write("        <p>V(View): inputNumber.jsp + showResult.jsp (视图)</p>\n");
      out.write("        <p>C(Controller): HandleComputer.java (Servlet控制器)</p>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
