/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.22
 * Generated at: 2026-06-16 07:16:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


    private int visitorCount = 0;
    private static final String[] FOODS = {"苹果", "香蕉", "橘子", "葡萄", "西瓜"};

    public String getGreeting() {
        int hour = java.time.LocalTime.now().getHour();
        if (hour < 12) return "早上好";
        else if (hour < 18) return "下午好";
        else return "晚上好";
    }

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>实验四 JSP脚本元素的应用</title>\n");
      out.write("    <style>\n");
      out.write("        body { font-family: Arial, sans-serif; margin: 20px auto; width: 650px; }\n");
      out.write("        h1 { text-align: center; color: #333; }\n");
      out.write("        .section { background: #f5f5f5; padding: 15px; margin: 10px 0; border-radius: 8px; }\n");
      out.write("        .section h3 { color: #006633; margin-top: 0; }\n");
      out.write("        table { border-collapse: collapse; width: 100%; }\n");
      out.write("        table, th, td { border: 1px solid #ddd; }\n");
      out.write("        th, td { padding: 8px; text-align: center; }\n");
      out.write("        th { background-color: #009966; color: white; }\n");
      out.write("        .info { color: #0066cc; font-weight: bold; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <h1>JSP脚本元素的应用</h1>\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    <div class=\"section\">\n");
      out.write("        <h3>1. JSP表达式 (&lt;%= %&gt;)</h3>\n");
      out.write("        <p>当前时间：");
      out.print( new java.util.Date() );
      out.write("</p>\n");
      out.write("        <p class=\"info\">问候语：");
      out.print( getGreeting() );
      out.write("！欢迎访问本页面！</p>\n");
      out.write("        <p>服务器信息：");
      out.print( application.getServerInfo() );
      out.write("</p>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    <div class=\"section\">\n");
      out.write("        <h3>2. JSP程序片 (&lt;% %&gt;)</h3>\n");
      out.write("        <p>水果列表（使用scriptlet循环输出）：</p>\n");
      out.write("        <table>\n");
      out.write("            <tr><th>序号</th><th>水果名称</th><th>推荐指数</th></tr>\n");
      out.write("            ");

                for (int i = 0; i < FOODS.length; i++) {
                    int stars = (int)(Math.random() * 5) + 1;
                    out.println("<tr>");
                    out.println("<td>" + (i + 1) + "</td>");
                    out.println("<td>" + FOODS[i] + "</td>");
                    out.println("<td>");
                    for (int j = 0; j < stars; j++) out.print("★");
                    for (int j = stars; j < 5; j++) out.print("☆");
                    out.println("</td>");
                    out.println("</tr>");
                }
            
      out.write("\n");
      out.write("        </table>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    <div class=\"section\">\n");
      out.write("        <h3>3. JSP声明 (&lt;%! %&gt;)</h3>\n");
      out.write("        ");

            visitorCount++;
        
      out.write("\n");
      out.write("        <p class=\"info\">您是第 ");
      out.print( visitorCount );
      out.write(" 位访问者（应用范围内计数）</p>\n");
      out.write("        <p>注：此计数基于JSP成员变量，每次刷新页面都会增加</p>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    <div class=\"section\">\n");
      out.write("        <h3>4. JSP与HTML混合使用</h3>\n");
      out.write("        ");

            String[] colors = {"#FF6B6B", "#4ECDC4", "#45B7D1", "#96CEB4", "#FFEAA7"};
            String[] names = {"红色系", "青色系", "蓝色系", "绿色系", "黄色系"};
        
      out.write("\n");
      out.write("        <table>\n");
      out.write("            <tr><th>颜色名称</th><th>颜色值</th><th>预览</th></tr>\n");
      out.write("            ");
 for (int i = 0; i < colors.length; i++) { 
      out.write("\n");
      out.write("            <tr>\n");
      out.write("                <td>");
      out.print( names[i] );
      out.write("</td>\n");
      out.write("                <td>");
      out.print( colors[i] );
      out.write("</td>\n");
      out.write("                <td style=\"background-color: ");
      out.print( colors[i] );
      out.write("; width: 100px;\">&nbsp;</td>\n");
      out.write("            </tr>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </table>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <p style=\"text-align:center; color:#888; font-size:12px;\">\n");
      out.write("        JSP脚本元素实验 - 演示声明、表达式、程序片的使用\n");
      out.write("    </p>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
